# Generated by Django 4.1 on 2023-01-12 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('related_person_name', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('licence_date', models.DateTimeField(default=datetime.datetime.now)),
                ('license_status', models.BooleanField(default=True)),
                ('date_last_updated', models.DateTimeField(auto_now_add=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(default=uuid.UUID('1859b103-92a7-11ed-bc02-b42e9935920a'), max_length=64)),
                ('data_last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('apartments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.apartments')),
            ],
            options={
                'unique_together': {('apartments', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='accounts.devices')),
            ],
            options={
                'unique_together': {('devices', 'name')},
            },
        ),
    ]
